/**
 * Reference geography for Bangladesh delivery. Fees are NOT defined here —
 * they live in the Supabase settings table and are editable in the admin panel.
 */
export type BdDistrict = { name: string; zone: string };

export const BD_DISTRICTS: BdDistrict[] = [
  { name: "Chattogram", zone: "chittagong" },
  { name: "Cox's Bazar", zone: "chittagong" },
  { name: "Cumilla", zone: "chittagong" },
  { name: "Brahmanbaria", zone: "chittagong" },
  { name: "Chandpur", zone: "chittagong" },
  { name: "Feni", zone: "chittagong" },
  { name: "Noakhali", zone: "chittagong" },
  { name: "Lakshmipur", zone: "chittagong" },
  { name: "Rangamati", zone: "chittagong" },
  { name: "Bandarban", zone: "chittagong" },
  { name: "Khagrachhari", zone: "chittagong" },
  { name: "Dhaka", zone: "other" },
  { name: "Gazipur", zone: "other" },
  { name: "Narayanganj", zone: "other" },
  { name: "Narsingdi", zone: "other" },
  { name: "Manikganj", zone: "other" },
  { name: "Munshiganj", zone: "other" },
  { name: "Tangail", zone: "other" },
  { name: "Kishoreganj", zone: "other" },
  { name: "Faridpur", zone: "other" },
  { name: "Gopalganj", zone: "other" },
  { name: "Madaripur", zone: "other" },
  { name: "Rajbari", zone: "other" },
  { name: "Shariatpur", zone: "other" },
  { name: "Sylhet", zone: "other" },
  { name: "Habiganj", zone: "other" },
  { name: "Moulvibazar", zone: "other" },
  { name: "Sunamganj", zone: "other" },
  { name: "Rajshahi", zone: "other" },
  { name: "Bogura", zone: "other" },
  { name: "Pabna", zone: "other" },
  { name: "Sirajganj", zone: "other" },
  { name: "Natore", zone: "other" },
  { name: "Joypurhat", zone: "other" },
  { name: "Chapainawabganj", zone: "other" },
  { name: "Naogaon", zone: "other" },
  { name: "Khulna", zone: "other" },
  { name: "Jashore", zone: "other" },
  { name: "Satkhira", zone: "other" },
  { name: "Bagerhat", zone: "other" },
  { name: "Kushtia", zone: "other" },
  { name: "Chuadanga", zone: "other" },
  { name: "Jhenaidah", zone: "other" },
  { name: "Magura", zone: "other" },
  { name: "Meherpur", zone: "other" },
  { name: "Narail", zone: "other" },
  { name: "Barishal", zone: "other" },
  { name: "Patuakhali", zone: "other" },
  { name: "Bhola", zone: "other" },
  { name: "Pirojpur", zone: "other" },
  { name: "Barguna", zone: "other" },
  { name: "Jhalokati", zone: "other" },
  { name: "Rangpur", zone: "other" },
  { name: "Dinajpur", zone: "other" },
  { name: "Gaibandha", zone: "other" },
  { name: "Kurigram", zone: "other" },
  { name: "Lalmonirhat", zone: "other" },
  { name: "Nilphamari", zone: "other" },
  { name: "Panchagarh", zone: "other" },
  { name: "Thakurgaon", zone: "other" },
  { name: "Mymensingh", zone: "other" },
  { name: "Jamalpur", zone: "other" },
  { name: "Netrokona", zone: "other" },
  { name: "Sherpur", zone: "other" },
].sort((a, b) => a.name.localeCompare(b.name));

export function zoneForDistrict(district: string): string {
  const match = BD_DISTRICTS.find((d) => d.name.toLowerCase() === district.trim().toLowerCase());
  return match?.zone ?? "other";
}
